# Get user info
GET https://api.github.com/users/octocat

###

# List repos

### List Octocat's Repositories
GET https://api.github.com/users/octocat/repos

###

# Get a single repo details

### Get a Specific Repository
GET https://api.github.com/repos/octocat/Hello-World
Accept: application/vnd.github.v3+json

###
